#!/usr/bin/env python3
"""Regenerate the interactive-reconstructions cards in index.html.

The cards carry per-scene numbers, so they are generated from the manifest
that export_web.py writes rather than hand-kept in sync.  Everything between
the BEGIN/END markers in index.html is replaced.
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BEGIN = "<!-- BEGIN recon-cards (generated by tools/render_section.py) -->"
END = "<!-- END recon-cards -->"

# The grid is unlabelled by design: the teaser above names its scenes, and
# repeating dataset, camera and point counts under every tile crowded it.
CARD = """      <figure class="recon" data-key="{key}" data-src="static/recon/{key}.vgpa">
        <div class="recon__stage">
          <img class="recon__poster" src="static/recon/{key}.jpg"
               alt="Reconstruction of {label}: recovered 3D points with the estimated cameras in red."
               loading="lazy" decoding="async" width="560" height="380">
          <button class="recon__go" type="button">Explore in 3D</button>
        </div>
      </figure>
"""


def meta_for(s):
    bits = [s["dataset"]]
    if s.get("n_input"):
        bits.append("%s of %s images" % (f(s["n_registered"]), f(s["n_input"])))
    else:
        bits.append("%s cameras" % f(s["n_registered"]))
    bits.append("%s points" % f(s["n_points"]))
    return " &middot; ".join(bits)


def f(n):
    return "{:,}".format(int(n))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest",
                    default=os.path.join(HERE, "..", "static", "recon", "scenes.json"))
    ap.add_argument("--html", default=os.path.join(HERE, "..", "index.html"))
    args = ap.parse_args()

    with open(args.manifest) as fh:
        scenes = json.load(fh)
    shown = [s for s in scenes if s.get("grid", True)]
    cards = "".join(CARD.format(key=s["key"], label=s["label"], meta=meta_for(s))
                    for s in shown)
    block = "%s\n%s    %s" % (BEGIN, cards, END)

    with open(args.html) as fh:
        html = fh.read()
    i, j = html.find(BEGIN), html.find(END)
    if i < 0 or j < 0:
        raise SystemExit("markers not found in %s" % args.html)
    html = html[:i] + block + html[j + len(END):]
    with open(args.html, "w") as fh:
        fh.write(html)
    print("wrote %d of %d scenes as cards into %s"
      % (len(shown), len(scenes), os.path.relpath(args.html)))


if __name__ == "__main__":
    main()
